const bwlFragen = [
    { "q": "Die doppelte Buchhaltung bietet mehr Sicherheit als die einfache Buchhaltung.", "a": true },
    { "q": "Durch die Einführung des „Wechsels“ konnte auf den Geldtransport nicht verzichtet werden.", "a": false },
    { "q": "Betriebsstoffe gehen nicht substanziell in die Produktion ein.", "a": true },
    { "q": "Die Entlobung ist eine zweiseitige Willenserklärung.", "a": false },
    { "q": "Das BGB ist ein Spezialgesetz, dass das HGB konkretisiert.", "a": false },
    { "q": "Die Rechtsfähigkeit beginnt mit der Vollendung der Geburt.", "a": true },
    { "q": "Patente und Lizenzen sind materielle Vermögensgegenstände.", "a": false },
    { "q": "Der primäre Sektor ist der Dienstleistungsbereich.", "a": false },
    { "q": "Bilder und Zeichen gehören zu den Werbemitteln.", "a": true },
    { "q": "Zahlungsverzug ist eine Störung bei der Erfüllung eines Kaufvertrages.", "a": false },
    { "q": "Die Werbung ist Teil des Public-Relations.", "a": false },
    { "q": "Der Besitzer einer Sache ist nicht immer auch der Eigentümer.", "a": true },
    { "q": "Durch just-in-time Lieferungen kann im Lager gebundenes Kapital nicht reduziert werden.", "a": false },
    { "q": "Beim Minimalprinzip ist die Faktoreinsatzmenge fix.", "a": false },
    { "q": "Hypothekenkredite sind kurzfristiges Fremdkapital.", "a": false },
    { "q": "Das klimatisieren einer Ware verursacht Lagerkosten.", "a": true },
    { "q": "Lizenzen sind keine handelbaren Rechte.", "a": false },
    { "q": "Rechtsfähig werden natürliche Personen mit 7 Jahren.", "a": false },
    { "q": "Der dipositive Faktor beinhaltet die Leitungstätigkeit.", "a": true },
    { "q": "Bei freien Gütern entsteht der Preis durch Angebot und Nachfrage.", "a": false },
    { "q": "Die doppelte Buchhaltung ist über 3000 Jahre alt.", "a": false },
    { "q": "Das Ergebnis des Mini-Max-Prinzips ist Null.", "a": false },
    { "q": "Betriebsstoffe gehen substanziell in die Produktion ein.", "a": false },
    { "q": "Die Rechtsfähigkeit beginnt mit Vollendung der Geburt.", "a": true },
    { "q": "Kinder zwischen 7 und 18 Jahren sind beschränkt geschäftsfähige Personen.", "a": true },
    { "q": "Unter dem sekundären Sektor versteht man die Urgewinnung.", "a": false },
    { "q": "Beim Polypol gibt es viele Anbieter und viele Nachfrager.", "a": true },
    { "q": "Das BGB ist dem HGB untergeordnet.", "a": false },
    { "q": "Just in Time Lieferung erhöht das Produktionsstillstandsrisiko.", "a": true },
    { "q": "Zweiseitige Rechtsgeschäfte benötigen zwei übereinstimmende Willenserklärungen.", "a": true },
    { "q": "Die Hauptversammlung einer AG wählt den Aufsichtsrat.", "a": true },
    { "q": "Warenschulden sind Holschulden, Geldschulden sind Bringschulden.", "a": true },
    { "q": "Hypothekarkredite sind langfristiges Fremdkapital.", "a": true },
    { "q": "Kostenstellen werden auf Kostenarten verteilt.", "a": false },
    { "q": "Bei einer OHG haftet auch das Privatvermögen der Inhaber.", "a": true },
    { "q": "Kapitalgesellschaften werden in der Abteilung B des Handelsregisters eingetragen.", "a": true },
    { "q": "Der Vorstand einer großen AG besteht zur Hälfte aus Arbeitnehmervertretern.", "a": false },
    { "q": "Die Distributionspolitik gehört zum Marketing-Mix.", "a": true },
    { "q": "Am Ende des Produktlebenszyklus steht die Produktinnovation.", "a": false },
    { "q": "Arbeiten am Lagergut gehören zu den Lagerkosten.", "a": true },
    { "q": "Die einfache Buchhaltung wird auch „Einnahme-/Ausgabenrechnung“ genannt.", "a": true },
    { "q": "Beim ökonomischen Prinzip folgt man dem Mini- oder Maximal-Prinzip.", "a": true },
    { "q": "Hilfsstoffe gehen substanziell in die Produktion ein.", "a": true },
    { "q": "Ein Fötus ist bereits erbfähig.", "a": true },
    { "q": "Der Taschengeldparagraph betrifft beschränkt geschäftsfähige Personen.", "a": true },
    { "q": "Unter dem primären Sektor versteht man den Dienstleistungsbereich.", "a": false },
    { "q": "Beim Polypol gibt es einen Anbieter und einen Nachfrager.", "a": false },
    { "q": "Just in Time Lieferung erhöht die Lagerhaltung.", "a": false },
    { "q": "Einseitige Rechtsgeschäfte benötigen zwei übereinstimmende Willenserklärungen.", "a": false },
    { "q": "Die Hauptversammlung einer AG wählt den Vorstand.", "a": false },
    { "q": "Beim einseitigen Handelskauf kann der Gerichtsstand frei vereinbart werden.", "a": false },
    { "q": "Lieferantenkredite sind langfristiges Fremdkapital.", "a": false },
    { "q": "Ein Aktionär hat kein Anrecht am Liquidationserlös.", "a": false },
    { "q": "Bei Kapitalgesellschaften haftet auch das Privatvermögen der Inhaber.", "a": false },
    { "q": "Kapitalgesellschaften werden in der Abteilung A des Handelsregisters eingetragen.", "a": false },
    { "q": "Warenschulden sind Bringschulden, Geldschulden sind Holschulden.", "a": false },
    { "q": "Am Ende des Produktlebenszyklus steht die Produktvariation.", "a": false },
    { "q": "Public-Relations ist Teil der Produktpolitik.", "a": false },
    { "q": "Bei einem Konto ist die linke Seite „Haben“ und die rechte Seite „Soll“.", "a": false },
    { "q": "Die Aktivseite der Bilanz zeigt die Mittelherkunft, die Passivseite die Mittelverwendung.", "a": false },
    { "q": "Das BGB ist ein Spezialgesetz, daß das HGB konkretisiert.", "a": false },
    { "q": "Die Geschäftsfähigkeit beginnt mit der Vollendung der Geburt.", "a": false },
    { "q": "Patente sind keine handelbaren Vermögensgegenstände.", "a": false },
    { "q": "Das klimatisieren von Waren verursacht keine Lagerkosten.", "a": false },
    { "q": "Der dispositive Faktor ist die ausführende Arbeit.", "a": false },
    { "q": "Substitutionsprodukte ergänzen andere Produkte.", "a": false },
    { "q": "In einem bilateralen Oligopol gibt es einen Anbieter und viele Nachfrager.", "a": false },
    { "q": "Beim Leihvertrag muß Besitz und Eigentum übertragen werden.", "a": false },
    { "q": "Die just-in-time Lieferung wurde im 21. Jahrhundert erfunden.", "a": false },
    { "q": "Hypothekenkredite sind kurzfristiges Fremdkapital.", "a": true },
    { "q": "Grundstücke und Gebäude gehören zum Umlaufvermögen.", "a": false },
    { "q": "In einer KG haftet nur das eingezahlte Kapital.", "a": false },
    { "q": "Das Handelsregister wir beim Landgericht geführt.", "a": false },
    { "q": "Komplementärprodukte ersetzten andere Produkte.", "a": false },
    { "q": "Die doppelte Buchhaltung bietet weniger Sicherheit als die einfache Buchhaltung.", "a": false },
    { "q": "Die Entlobung ist eine einseitige nicht empfangsbedürftige Willenserklärung.", "a": true },
    { "q": "Das HGB ist dem BGB übergeordnet.", "a": false },
    { "q": "Der tertiäre Sektor ist der Dienstleistungsbereich.", "a": true },
    { "q": "Lieferverzug ist eine Störung bei der Erfüllung eines Kaufvertrages.", "a": true },
    { "q": "Die Werbung ist Teil der Kommunikationspolitik.", "a": true },
    { "q": "Der Eigentümer einer Sache ist nicht immer auch der Besitzer.", "a": true },
    { "q": "Durch just-in-time Lieferungen kann im Lager gebundenes Kapital reduziert werden.", "a": true },
    { "q": "Beim Minimalprinzip ist die Faktoreinsatzmenge variabel.", "a": true },
    { "q": "Hypothekenkredite sind langfristiges Fremdkapital.", "a": true },
    { "q": "Das Kommissionieren einer Ware verursacht Lagerkosten.", "a": true },
    { "q": "Lizenzen sind handelbaren Rechte.", "a": true },
    { "q": "Im vollkommenen Markt ist der Preis ein Datum.", "a": true },
    { "q": "Im bilateralen Oligopol gibt es wenige Anbieter und wenige Nachfrager.", "a": true },
    { "q": "Die Volkswirtschaftslehre ist älter als die Betriebswirtschaftslehre.", "a": true }
];